# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv_store.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ekv_store.proto\x12\x08kv_store\"4\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\t\"\"\n\x0fSuccessResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"+\n\x07Replica\x12\x12\n\nip_address\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x32\xa0\x01\n\rKeyValueStore\x12,\n\x05write\x12\x12.kv_store.KeyValue\x1a\r.kv_store.Key\"\x00\x12+\n\x04read\x12\r.kv_store.Key\x1a\x12.kv_store.KeyValue\"\x00\x12\x34\n\x06\x64\x65lete\x12\r.kv_store.Key\x1a\x19.kv_store.SuccessResponse\"\x00\x42\"\n\x10\x63om.example.grpcB\x0cKVStoreProtoP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kv_store_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\020com.example.grpcB\014KVStoreProtoP\001'
  _KEYVALUE._serialized_start=28
  _KEYVALUE._serialized_end=80
  _KEY._serialized_start=82
  _KEY._serialized_end=100
  _SUCCESSRESPONSE._serialized_start=102
  _SUCCESSRESPONSE._serialized_end=136
  _REPLICA._serialized_start=138
  _REPLICA._serialized_end=181
  _KEYVALUESTORE._serialized_start=184
  _KEYVALUESTORE._serialized_end=344
# @@protoc_insertion_point(module_scope)
