# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registry.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eregistry.proto\x12\x08registry\"#\n\x07Process\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"+\n\x0fRegisterRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"^\n\x10RegisterResponse\x12\x12\n\nis_primary\x18\x01 \x01(\x08\x12\x19\n\x11primary_server_ip\x18\x02 \x01(\t\x12\x1b\n\x13primary_server_port\x18\x03 \x01(\x05\"\x15\n\x13GetProcessesRequest\"<\n\x14GetProcessesResponse\x12$\n\tprocesses\x18\x01 \x03(\x0b\x32\x11.registry.Process\"\'\n\x11UnregisterRequest\x12\x12\n\nprocess_id\x18\x01 \x01(\t\"\x14\n\x12UnregisterResponse2\xeb\x01\n\x08Registry\x12\x43\n\x08Register\x12\x19.registry.RegisterRequest\x1a\x1a.registry.RegisterResponse\"\x00\x12O\n\x0cGetProcesses\x12\x1d.registry.GetProcessesRequest\x1a\x1e.registry.GetProcessesResponse\"\x00\x12I\n\nUnregister\x12\x1b.registry.UnregisterRequest\x1a\x1c.registry.UnregisterResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'registry_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROCESS._serialized_start=28
  _PROCESS._serialized_end=63
  _REGISTERREQUEST._serialized_start=65
  _REGISTERREQUEST._serialized_end=108
  _REGISTERRESPONSE._serialized_start=110
  _REGISTERRESPONSE._serialized_end=204
  _GETPROCESSESREQUEST._serialized_start=206
  _GETPROCESSESREQUEST._serialized_end=227
  _GETPROCESSESRESPONSE._serialized_start=229
  _GETPROCESSESRESPONSE._serialized_end=289
  _UNREGISTERREQUEST._serialized_start=291
  _UNREGISTERREQUEST._serialized_end=330
  _UNREGISTERRESPONSE._serialized_start=332
  _UNREGISTERRESPONSE._serialized_end=352
  _REGISTRY._serialized_start=355
  _REGISTRY._serialized_end=590
# @@protoc_insertion_point(module_scope)
